version: "3"
services:
  db:
    image: mysql:8.0.31
    volumes:
      - docker-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "8306:3306"
volumes:
  docker-mysql-data: